apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  labels:
    app: hello-world-rest-api
  name: hello-world-rest-api
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-rest-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-world-rest-api
    spec:
      containers:
      - image: hello-world
        imagePullPolicy: IfNotPresent
        name: hello-world-rest-api
        envFrom:
          - configMapRef:
              name: hello-world-rest-api
#        env:
#          - name : HELLOW-WORLD-STRING-MESSAGE
#            value : OLA !! BOM DIA
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    app: hello-world-rest-api
  name: hello-world-rest-api
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-world-rest-api
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
data:
  MESSAGE_STRING: BOMDIA
kind: ConfigMap
metadata:
  name: hello-world-rest-api
  namespace: default  
