INSERT INTO USER_DETAILS(ID,BIRTHDATE,NAME) VALUES(1001,current_date(),'Don');
INSERT INTO USER_DETAILS(ID,BIRTHDATE,NAME) VALUES(1002,current_date(),'Groove');
INSERT INTO USER_DETAILS(ID,BIRTHDATE,NAME) VALUES(1003,current_date(),'Minion');
INSERT INTO USER_DETAILS(ID,BIRTHDATE,NAME) VALUES(1004,current_date(),'Donna');
INSERT INTO USER_DETAILS(ID,BIRTHDATE,NAME) VALUES(1005,current_date(),'Jesper');