INSERT INTO USER_DETAILS(ID,BIRTHDATE,NAME) VALUES(1,current_date(),'Don');
INSERT INTO USER_DETAILS(ID,BIRTHDATE,NAME) VALUES(2,current_date(),'Groove');
INSERT INTO USER_DETAILS(ID,BIRTHDATE,NAME) VALUES(3,current_date(),'Minion');
INSERT INTO USER_DETAILS(ID,BIRTHDATE,NAME) VALUES(4,current_date(),'Donna');
INSERT INTO USER_DETAILS(ID,BIRTHDATE,NAME) VALUES(5,current_date(),'Jesper');
INSERT INTO POST(ID,DESCRIPTION,USER_ID) VALUES(2001,'I want to learn AWS and azure',1);
INSERT INTO POST(ID,DESCRIPTION,USER_ID) VALUES(2002,'I want to learn GCP',1);
INSERT INTO POST(ID,DESCRIPTION,USER_ID) VALUES(2003,'I want to learn Data Bit',2);
INSERT INTO POST(ID,DESCRIPTION,USER_ID) VALUES(2004,'I want to learn BIgQuery',2);