INSERT INTO USER_DETAILS(id,name,address) VALUES(1,'HARMEET','BERLIN');
INSERT INTO USER_DETAILS(id,name,address) VALUES(2,'HARGEET','BERLIN');
INSERT INTO USER_DETAILS(id,name,address) VALUES(3,'HARJEET','BERLIN');