INSERT INTO USER_DETAILS(ID,NAME,ADDRESS) VALUES(1,'HAR MEET','BERLIN');
INSERT INTO USER_DETAILS(ID,NAME,ADDRESS) VALUES(2,'TARGET','BERLIN');
INSERT INTO USER_DETAILS(ID,NAME,ADDRESS) VALUES(3,'HARJEET','BERLIN');