INSERT INTO USER_DETAILS(ID,NAME,ADDRESS) VALUES(1,'HARMEET','BERLIN');
INSERT INTO USER_DETAILS(ID,NAME,ADDRESS) VALUES(2,'TARGET','MOSCO');
INSERT INTO USER_DETAILS(ID,NAME,ADDRESS) VALUES(3,'HARGEET','MEXICO');
INSERT INTO USER_DETAILS(ID,NAME,ADDRESS) VALUES(4,'MEET','US');
INSERT INTO USER_DETAILS(ID,NAME,ADDRESS) VALUES(5,'JEET','CANADA');
INSERT INTO USER_DETAILS(ID,NAME,ADDRESS) VALUES(6,'REET','BOLIVIA');
INSERT INTO USER_DETAILS(ID,NAME,ADDRESS) VALUES(7,'HARMEET','TORONTO');
INSERT INTO USER_DETAILS(ID,NAME,ADDRESS) VALUES(8,'HARMEET','AUSTRIA');
INSERT INTO USER_DETAILS(ID,NAME,ADDRESS) VALUES(9,'HARMEET','AUSTRALIA');
INSERT INTO USER_DETAILS(ID,NAME,ADDRESS) VALUES(10,'MEET','AUSTRALIA');
INSERT INTO USER_DETAILS(ID,NAME,ADDRESS) VALUES(11,'JEET','AUSTRALIA');
INSERT INTO USER_DETAILS(ID,NAME,ADDRESS) VALUES(12,'HARGEET','AUSTRALIA');

